### ISSUE TITLE
Добавить нотификацию

### ISSUE THREAD

**Issue by anry-das** [ToshnoWor/nctaskmanager#3]
Согласно требованиям к работе, в проекте должна быть нотификация - при наступлении времени события необходимо выводить сообщение в консоль.
Для этого удобно использовать поток-демон.

**Comment by ToshnoWor** [comment]
Issue#3: "Add notification"
commit: 3e74ebfaab3efa75210a4d8bccd69acd6e69bf55

**Comment by anry-das** [comment]
После запуска проекта падает ошибка
```
Exception in thread "Thread-0" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at ua.edu.sumdu.j2se.Koval.tasks.model.Model.getFirstInListToGo(Model.java:343)
	at ua.edu.sumdu.j2se.Koval.tasks.model.Model.getNextTaskToGo(Model.java:327)
	at ua.edu.sumdu.j2se.Koval.tasks.model.Model.Notification(Model.java:304)
	at ua.edu.sumdu.j2se.Koval.tasks.controller.Controller.Notification(Controller.java:185)
	at ua.edu.sumdu.j2se.Koval.tasks.modules.Notification.run(Notification.java:24)
```

**Comment by ToshnoWor** [comment]
Issue#3: "Add notification"
fix error: Exception in thread "Thread-0" java.lang.NullPointerException
commit: d4001b2a68ae9f3ccab6954f5a5b13d6e5344818
